version: '3.9'
services:
  db:
    container_name: ${DB_HOST:-resplice_db}
    image: 'postgres:alpine'
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-resplice_db}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - resplice_data:/var/lib/postgresql/data
    ports:
      - '5432:${DB_PORT:-5432}'
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '5050:80'
  # api:
  #   container_name: ${HOST}
  #   build: ./api
  #   environment:
  #     HOST: ${HOST}
  #     PORT: ${PORT}
  #     DB_HOST: ${DB_HOST}
  #     DB_SOCKET: ${DB_SOCKET}
  #     DB_PORT: ${DB_PORT}
  #     DB_NAME: ${DB_NAME}
  #     DB_USERNAME: ${DB_USERNAME}
  #     DB_PASSWORD: ${DB_PASSWORD}
  #     ENCRYPTION_KEYS: ${ENCRYPTION_KEYS}
  #     HASH_KEY: ${HASH_KEY}
  #   ports:
  #     - "${PORT}:${PORT}"
  #   volumes:
  #     - ./api:/api
  #   depends_on:
  #     - db
  resplice-ui:
    container_name: resplice-ui
    build: ./web/r-apps/resplice
    ports:
      - 3000:3000
    depends_on:
      - api
  reauth-ui:
    container_name: reauth-ui
    build: ./web/r-apps/reauth
    ports:
      - 3010:3000
    depends_on:
      - api

volumes:
  resplice_data: {}

networks:
  default:
    name: resplice
