version: '3'
services:
  db:
    container_name: ${DB_HOST}
    image: "postgres:alpine"
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-resplice_db}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - resplice_db:/var/lib/postgresql/data
    ports:
      - "54321:${DB_PORT}"
  api:
    container_name: ${HOST}
    build: ./api.resplice.com
    environment:
      HOST: ${HOST}
      PORT: ${PORT}
      DB_HOST: ${DB_HOST}
      DB_SOCKET: ${DB_SOCKET}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      ENCRYPTION_KEYS: ${ENCRYPTION_KEYS}
      HASH_KEY: ${HASH_KEY}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./api:/api
    depends_on:
      - db
  ui:
    container_name: resplice-ui
    build: ./www
    ports:
      - 3000:3000
    depends_on:
      - api

volumes:
    resplice_data: {}
